export const TOGGLE_OPEN_INCIDENT = 'TOGGLE_OPEN_INCIDENT';
export const TOGGLE_CLOSED_INCIDENT = 'TOGGLE_CLOSED_INCIDENT';
export const TOGGLE_OPENTODAY = 'TOGGLE_OPENTODAY';
export const TOGGLE_OPENYESTERDAY = 'TOGGLE_OPENYESTERDAY';
